/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ClozeReviewPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  lang: "auto",
  apiEndpoint: "https://api.openai.com/v1/chat/completions",
  apiKey: "",
  model: "gpt-4o-mini",
  customPrompt: "",
  difficulty: "medium",
  temperature: 0.3,
  autoEnterReview: true
};
var ClozeReviewSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    __publicField(this, "plugin");
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const t = this.plugin.t;
    containerEl.createEl("h3", { text: t.language });
    new import_obsidian.Setting(containerEl).setName(t.language).setDesc(t.languageDesc).addDropdown(
      (dropdown) => dropdown.addOption("auto", t.languageDesc).addOption("zh", t.chinese).addOption("en", t.english).setValue(this.plugin.settings.lang).onChange(async (value) => {
        this.plugin.settings.lang = value;
        await this.plugin.saveSettings();
        this.plugin.updateLang();
        this.display();
      })
    );
    containerEl.createEl("h3", { text: t.aiConfig });
    new import_obsidian.Setting(containerEl).setName(t.apiEndpoint).setDesc(t.apiEndpointDesc).addText(
      (text) => text.setPlaceholder("https://api.openai.com/v1/chat/completions").setValue(this.plugin.settings.apiEndpoint).onChange(async (value) => {
        this.plugin.settings.apiEndpoint = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.apiKey).setDesc(t.apiKeyDesc).addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("sk-...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName(t.model).setDesc(t.modelDesc).addText(
      (text) => text.setPlaceholder("gpt-4o-mini").setValue(this.plugin.settings.model).onChange(async (value) => {
        this.plugin.settings.model = value;
        await this.plugin.saveSettings();
      })
    ).addButton(
      (button) => button.setButtonText(t.testConnection).onClick(async () => {
        this.plugin.aiService.updateSettings(this.plugin.settings);
        button.setButtonText(t.testing);
        button.setDisabled(true);
        try {
          await this.plugin.aiService.testConnection();
          new import_obsidian.Notice(t.testSuccess);
        } catch (e) {
          new import_obsidian.Notice(t.testFailed + e.message, 5e3);
        } finally {
          button.setButtonText(t.testConnection);
          button.setDisabled(false);
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.temperature).setDesc(t.temperatureDesc).addSlider(
      (slider) => slider.setLimits(0, 1, 0.1).setValue(this.plugin.settings.temperature).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.temperature = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: t.clozeSettings });
    new import_obsidian.Setting(containerEl).setName(t.difficulty).setDesc(t.difficultyDesc).addDropdown(
      (dropdown) => dropdown.addOption("easy", t.easy).addOption("medium", t.medium).addOption("hard", t.hard).addOption("extreme", t.extreme).setValue(this.plugin.settings.difficulty).onChange(async (value) => {
        this.plugin.settings.difficulty = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.autoReview).setDesc(t.autoReviewDesc).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoEnterReview).onChange(async (value) => {
        this.plugin.settings.autoEnterReview = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.customPrompt).setDesc(t.customPromptDesc).addTextArea((text) => {
      text.setPlaceholder(this.plugin.t.defaultPrompt).setValue(this.plugin.settings.customPrompt).onChange(async (value) => {
        this.plugin.settings.customPrompt = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 10;
      text.inputEl.style.width = "100%";
    });
    const hintEl = containerEl.createEl("div", { cls: "cloze-review-hint" });
    hintEl.innerHTML = `
			<p><strong>${t.clozeSyntax}\uFF1A</strong></p>
			<ul>
				<li><code>{{c1::\u5185\u5BB9}}</code> - ${t.basicCloze}</li>
				<li><code>{{c1::\u5185\u5BB9::\u63D0\u793A}}</code> - ${t.hintCloze}</li>
			</ul>
			<p>${t.autoCalc}</p>
			<p>${t.readingDesc}</p>
		`;
  }
};

// src/ai-service.ts
var import_obsidian2 = require("obsidian");
var DIFFICULTY_DENSITY = {
  easy: 250,
  medium: 120,
  hard: 60,
  extreme: 30
};
function getDifficultyHint(difficulty, t) {
  switch (difficulty) {
    case "easy":
      return t.diffHintEasy;
    case "hard":
      return t.diffHintHard;
    case "extreme":
      return t.diffHintExtreme;
    default:
      return t.diffHintMedium;
  }
}
var AIService = class {
  constructor(settings) {
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  async testConnection() {
    var _a;
    if (!this.settings.apiEndpoint) {
      throw new Error("No API endpoint");
    }
    if (!this.settings.apiKey) {
      throw new Error("No API key");
    }
    if (!this.settings.model) {
      throw new Error("No model");
    }
    const body = JSON.stringify({
      model: this.settings.model,
      messages: [{ role: "user", content: "Hi" }],
      max_tokens: 5
    });
    const response = await (0, import_obsidian2.requestUrl)({
      url: this.settings.apiEndpoint,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.settings.apiKey}`
      },
      body,
      throw: false
    });
    if (response.status >= 400) {
      let errorMsg = `API ${response.status}`;
      try {
        const errorJson = typeof response.json === "string" ? JSON.parse(response.json) : response.json;
        if ((_a = errorJson == null ? void 0 : errorJson.error) == null ? void 0 : _a.message) {
          errorMsg += `: ${errorJson.error.message}`;
        }
      } catch (e) {
        if (response.text)
          errorMsg += `: ${response.text.slice(0, 200)}`;
      }
      throw new Error(errorMsg);
    }
  }
  calcClozeCount(content) {
    const density = DIFFICULTY_DENSITY[this.settings.difficulty] || DIFFICULTY_DENSITY.medium;
    const count = Math.round(content.length / density);
    return Math.max(3, Math.min(count, 200));
  }
  async generateCloze(content, customPrompt, locale) {
    const difficultyHint = getDifficultyHint(this.settings.difficulty, locale);
    const targetCount = this.calcClozeCount(content);
    const clozeHint = locale.clozeCountHint.replace("{0}", String(targetCount));
    const basePrompt = customPrompt || locale.defaultPrompt;
    const systemMessage = `${basePrompt}

${difficultyHint}
${clozeHint}

${locale.systemSuffix}`;
    const chunks = this.splitContent(content, 3e3);
    const chunkTarget = Math.round(targetCount / chunks.length);
    const results = [];
    for (let i = 0; i < chunks.length; i++) {
      const chunkHint = chunks.length > 1 ? `
${locale.chunkHint.replace("{0}", String(chunkTarget))}` : "";
      const userMessage = `${locale.userMessagePrefix}${chunkHint}

${chunks[i]}`;
      const response = await this.callAPI(systemMessage, userMessage);
      results.push(this.extractContent(response));
    }
    return results.join("\n\n");
  }
  splitContent(content, maxLen) {
    if (content.length <= maxLen)
      return [content];
    const lines = content.split("\n");
    const chunks = [];
    let current = "";
    for (const line of lines) {
      if ((current + "\n" + line).length > maxLen && current) {
        chunks.push(current);
        current = line;
      } else {
        current = current ? current + "\n" + line : line;
      }
    }
    if (current)
      chunks.push(current);
    return chunks;
  }
  async callAPI(systemMessage, userMessage) {
    var _a;
    if (!this.settings.apiKey) {
      throw new Error("API key not configured");
    }
    const body = JSON.stringify({
      model: this.settings.model,
      messages: [
        { role: "system", content: systemMessage },
        { role: "user", content: userMessage }
      ],
      temperature: this.settings.temperature,
      max_tokens: 8192
    });
    const response = await (0, import_obsidian2.requestUrl)({
      url: this.settings.apiEndpoint,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.settings.apiKey}`
      },
      body,
      throw: false
    });
    if (response.status >= 400) {
      let errorMsg = `API ${response.status}`;
      try {
        const errorJson = typeof response.json === "string" ? JSON.parse(response.json) : response.json;
        if ((_a = errorJson == null ? void 0 : errorJson.error) == null ? void 0 : _a.message) {
          errorMsg += `: ${errorJson.error.message}`;
        }
      } catch (e) {
        if (response.text)
          errorMsg += `: ${response.text.slice(0, 200)}`;
      }
      throw new Error(errorMsg);
    }
    return response.json;
  }
  extractContent(response) {
    var _a, _b, _c;
    const content = (_c = (_b = (_a = response == null ? void 0 : response.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content;
    if (!content) {
      throw new Error("Empty AI response");
    }
    let result = content.trim();
    if (result.startsWith("```")) {
      result = result.replace(/^```(?:markdown)?\n?/, "").replace(/\n?```$/, "");
    }
    return result;
  }
};

// src/cloze-parser.ts
var CLOZE_REGEX = /\{\{c(\d+)::([\s\S]+?)\}\}/g;
var ClozeParser = class {
  findAll(text) {
    const matches = [];
    let match;
    const regex = new RegExp(CLOZE_REGEX);
    while ((match = regex.exec(text)) !== null) {
      const content = match[2];
      const parts = content.split("::");
      const answer = parts[0].trim();
      const hint = parts.length > 1 ? parts.slice(1).join("::").trim() : null;
      matches.push({
        fullMatch: match[0],
        id: match[1],
        answer,
        hint,
        start: match.index,
        end: regex.lastIndex
      });
    }
    return matches;
  }
  count(text) {
    const matches = this.findAll(text);
    return matches.length;
  }
  stripClozes(text) {
    return text.replace(CLOZE_REGEX, (_match, _id, content) => {
      const parts = content.split("::");
      return parts[0].trim();
    });
  }
  hasClozes(text) {
    return CLOZE_REGEX.test(text);
  }
};

// src/review-mode.ts
var import_obsidian3 = require("obsidian");
var CLOZE_REGEX2 = /\{\{c(\d+)::([\s\S]+?)\}\}/g;
var ReviewMode = class {
  constructor(app, plugin) {
    __publicField(this, "app");
    __publicField(this, "plugin");
    __publicField(this, "active", false);
    this.app = app;
    this.plugin = plugin;
  }
  getMarkdownView() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (activeView)
      return activeView;
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    if (leaves.length > 0)
      return leaves[0].view;
    return null;
  }
  isActive() {
    return this.active;
  }
  async activate(silent = false) {
    this.active = true;
    const view = this.getMarkdownView();
    if (!view || !view.file) {
      if (!silent)
        new import_obsidian3.Notice(this.plugin.t.openNoteFirst);
      this.active = false;
      return;
    }
    const clozeContent = this.plugin.clozeCache.get(view.file.path);
    if (!clozeContent) {
      if (!silent)
        new import_obsidian3.Notice(this.plugin.t.generateFirst);
      this.active = false;
      return;
    }
    if (view.getMode() !== "preview") {
      await view.setState({ mode: "preview" }, {});
      await new Promise((r) => setTimeout(r, 500));
    }
    await this.showClozeOverlay(view, clozeContent);
    this.applyReviewClass(view);
    if (!silent)
      new import_obsidian3.Notice(this.plugin.t.reviewOn);
  }
  async showClozeOverlay(view, content) {
    const previewEl = view.containerEl.querySelector(".markdown-preview-view");
    if (!previewEl)
      return;
    const originalSizer = previewEl.querySelector(".markdown-preview-sizer:not(.cloze-overlay)");
    if (originalSizer) {
      originalSizer.style.display = "none";
    }
    let overlay = previewEl.querySelector(".cloze-overlay");
    if (!overlay) {
      overlay = document.createElement("div");
      overlay.className = "markdown-preview-sizer markdown-preview-section cloze-overlay";
      previewEl.appendChild(overlay);
    }
    overlay.innerHTML = "";
    const pusher = document.createElement("div");
    pusher.className = "markdown-preview-pusher";
    overlay.appendChild(pusher);
    const contentDiv = document.createElement("div");
    overlay.appendChild(contentDiv);
    await import_obsidian3.MarkdownRenderer.renderMarkdown(
      content,
      contentDiv,
      view.file.path,
      this.plugin
    );
  }
  hideClozeOverlay(view) {
    const previewEl = view.containerEl.querySelector(".markdown-preview-view");
    if (!previewEl)
      return;
    const overlay = previewEl.querySelector(".cloze-overlay");
    if (overlay)
      overlay.remove();
    const originalSizer = previewEl.querySelector(".markdown-preview-sizer:not(.cloze-overlay)");
    if (originalSizer) {
      originalSizer.style.display = "";
    }
  }
  deactivate(silent = false) {
    this.active = false;
    const view = this.getMarkdownView();
    if (view) {
      this.hideClozeOverlay(view);
      this.removeReviewClass(view);
    }
    if (!silent)
      new import_obsidian3.Notice(this.plugin.t.reviewOff);
  }
  applyReviewClass(view) {
    if (!view)
      return;
    const previewEl = view.containerEl.querySelector(".markdown-preview-view");
    if (previewEl) {
      previewEl.classList.add("cloze-review-active");
      this.resetAll();
    }
  }
  removeReviewClass(view) {
    if (!view)
      return;
    const previewEl = view.containerEl.querySelector(".markdown-preview-view");
    if (previewEl) {
      previewEl.classList.remove("cloze-review-active");
      previewEl.querySelectorAll(".cloze-blank").forEach((el) => {
        el.classList.remove("cloze-revealed");
      });
    }
  }
  revealAll() {
    if (!this.active) {
      new import_obsidian3.Notice(this.plugin.t.activateFirst);
      return;
    }
    const view = this.getMarkdownView();
    if (!view)
      return;
    view.containerEl.querySelectorAll(".cloze-blank").forEach((el) => {
      el.classList.add("cloze-revealed");
    });
  }
  resetAll() {
    const view = this.getMarkdownView();
    if (!view)
      return;
    view.containerEl.querySelectorAll(".cloze-blank").forEach((el) => {
      el.classList.remove("cloze-revealed");
    });
  }
  getStats() {
    const view = this.getMarkdownView();
    if (!view)
      return { total: 0, revealed: 0 };
    const overlay = view.containerEl.querySelector(".cloze-overlay");
    if (!overlay)
      return { total: 0, revealed: 0 };
    const blanks = overlay.querySelectorAll(".cloze-blank");
    const revealed = overlay.querySelectorAll(".cloze-blank.cloze-revealed");
    return { total: blanks.length, revealed: revealed.length };
  }
  hasClozes() {
    const view = this.getMarkdownView();
    if (!view)
      return false;
    return view.containerEl.querySelectorAll(".cloze-blank").length > 0;
  }
  hasCachedClozes() {
    const view = this.getMarkdownView();
    if (!view || !view.file)
      return false;
    return this.plugin.clozeCache.has(view.file.path);
  }
  processElement(el) {
    if (!this.active)
      return;
    if (!el.closest(".cloze-overlay"))
      return;
    const walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT, {
      acceptNode(node2) {
        const parent = node2.parentElement;
        if (!parent)
          return NodeFilter.FILTER_REJECT;
        if (parent.closest("code, pre, .cloze-blank, .cloze-answer, .cloze-placeholder")) {
          return NodeFilter.FILTER_REJECT;
        }
        if (!node2.textContent || !node2.textContent.includes("{{c")) {
          return NodeFilter.FILTER_REJECT;
        }
        return NodeFilter.FILTER_ACCEPT;
      }
    });
    const textNodes = [];
    let node;
    while (node = walker.nextNode()) {
      textNodes.push(node);
    }
    for (const textNode of textNodes) {
      this.processTextNode(textNode);
    }
  }
  processTextNode(textNode) {
    const text = textNode.textContent;
    if (!text)
      return;
    const regex = new RegExp(CLOZE_REGEX2);
    let lastIndex = 0;
    let match;
    const fragments = [];
    let hasMatch = false;
    while ((match = regex.exec(text)) !== null) {
      hasMatch = true;
      if (match.index > lastIndex) {
        fragments.push(document.createTextNode(text.slice(lastIndex, match.index)));
      }
      const content = match[2];
      const parts = content.split("::");
      const answer = parts[0].trim();
      const hint = parts.length > 1 ? parts.slice(1).join("::").trim() : null;
      const clozeEl = this.createClozeElement(answer, hint);
      fragments.push(clozeEl);
      lastIndex = regex.lastIndex;
    }
    if (hasMatch) {
      if (lastIndex < text.length) {
        fragments.push(document.createTextNode(text.slice(lastIndex)));
      }
      const parent = textNode.parentElement;
      if (!parent)
        return;
      for (const frag of fragments) {
        parent.insertBefore(frag, textNode);
      }
      parent.removeChild(textNode);
    }
  }
  createClozeElement(answer, hint) {
    const el = document.createElement("span");
    el.className = "cloze-blank";
    const answerSpan = document.createElement("span");
    answerSpan.className = "cloze-answer";
    answerSpan.textContent = answer;
    el.appendChild(answerSpan);
    const placeholderSpan = document.createElement("span");
    placeholderSpan.className = "cloze-placeholder";
    placeholderSpan.textContent = hint ? `[${hint}]` : this.plugin.t.placeholder;
    el.appendChild(placeholderSpan);
    el.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      if (this.active) {
        el.classList.toggle("cloze-revealed");
        this.plugin.toolbar.refresh();
      }
    });
    return el;
  }
  destroy() {
    this.active = false;
    const view = this.getMarkdownView();
    if (view) {
      this.hideClozeOverlay(view);
      this.removeReviewClass(view);
    }
    document.querySelectorAll(".cloze-review-active").forEach((el) => {
      el.classList.remove("cloze-review-active");
    });
  }
};

// src/toolbar.ts
var import_obsidian4 = require("obsidian");
var BottomToolbar = class {
  constructor(app, plugin) {
    __publicField(this, "app");
    __publicField(this, "plugin");
    __publicField(this, "toolbarEl", null);
    __publicField(this, "statusEl", null);
    __publicField(this, "leftGroup", null);
    __publicField(this, "centerGroup", null);
    __publicField(this, "containerEl", null);
    this.app = app;
    this.plugin = plugin;
  }
  init() {
    this.app.workspace.onLayoutReady(() => {
      this.update();
    });
    this.app.workspace.on("active-leaf-change", () => {
      this.update();
    });
  }
  update() {
    const leaf = this.app.workspace.activeLeaf;
    if (!leaf || leaf.view.getViewType() !== "markdown") {
      this.hide();
      return;
    }
    this.show(leaf);
  }
  show(leaf) {
    this.hide();
    const view = leaf.view;
    const container = view.containerEl;
    container.classList.add("has-cloze-toolbar");
    this.containerEl = container;
    const toolbar = document.createElement("div");
    toolbar.className = "cloze-review-toolbar";
    this.leftGroup = document.createElement("div");
    this.leftGroup.className = "cloze-toolbar-group cloze-toolbar-left";
    this.statusEl = document.createElement("span");
    this.statusEl.className = "cloze-toolbar-status";
    this.statusEl.textContent = this.plugin.t.ready;
    this.leftGroup.appendChild(this.statusEl);
    this.leftGroup.appendChild(this.createIconButton("settings", () => {
      this.plugin.openSettings();
    }));
    this.centerGroup = document.createElement("div");
    this.centerGroup.className = "cloze-toolbar-group cloze-toolbar-center";
    toolbar.appendChild(this.leftGroup);
    toolbar.appendChild(this.centerGroup);
    container.appendChild(toolbar);
    this.toolbarEl = toolbar;
    this.refresh();
  }
  refresh() {
    if (!this.centerGroup)
      return;
    this.centerGroup.empty();
    const t = this.plugin.t;
    const generating = this.plugin.isGenerating();
    const reviewing = this.plugin.reviewMode.isActive();
    const hasCache = this.plugin.reviewMode.hasCachedClozes();
    if (generating) {
      this.centerGroup.appendChild(this.createButton(t.generating, "loader", () => {
      }, true));
    } else if (reviewing) {
      const stats = this.plugin.reviewMode.getStats();
      const allRevealed = stats.total > 0 && stats.revealed >= stats.total;
      this.centerGroup.appendChild(this.createButton(
        allRevealed ? t.reset : t.showAnswer,
        allRevealed ? "rotate-ccw" : "eye-off",
        () => {
          if (allRevealed) {
            this.plugin.reviewMode.resetAll();
          } else {
            this.plugin.reviewMode.revealAll();
          }
          this.refresh();
        }
      ));
      this.centerGroup.appendChild(this.createButton(t.exitReview, "x", () => {
        this.plugin.reviewMode.deactivate();
        this.refresh();
      }));
    } else {
      this.centerGroup.appendChild(this.createButton(t.aiGenerate, "sparkles", () => {
        this.plugin.generateCloze();
      }));
      if (hasCache) {
        this.centerGroup.appendChild(this.createButton(t.startReview, "play", () => {
          this.plugin.startReview();
        }));
      }
    }
    this.updateStatus(generating, reviewing, hasCache);
  }
  updateStatus(generating, reviewing, hasCache) {
    if (!this.statusEl)
      return;
    const t = this.plugin.t;
    if (generating) {
      this.statusEl.textContent = t.aiGenerating;
      this.statusEl.classList.add("generating");
      this.statusEl.classList.remove("reviewing");
    } else if (reviewing) {
      const stats = this.plugin.reviewMode.getStats();
      this.statusEl.textContent = `${stats.revealed} / ${stats.total}`;
      this.statusEl.classList.add("reviewing");
      this.statusEl.classList.remove("generating");
    } else if (hasCache) {
      const view = this.plugin.getMarkdownView();
      if (view && view.file) {
        const cached = this.plugin.clozeCache.get(view.file.path);
        if (cached) {
          const count = this.plugin.clozeParser.count(cached);
          this.statusEl.textContent = `${count} ${t.clozesCount}`;
        }
      }
      this.statusEl.classList.remove("reviewing", "generating");
    } else {
      this.statusEl.textContent = this.plugin.t.ready;
      this.statusEl.classList.remove("reviewing", "generating");
    }
  }
  createButton(label, iconName, onClick, disabled = false) {
    const btn = document.createElement("button");
    btn.className = "cloze-toolbar-btn";
    if (iconName === "loader") {
      btn.classList.add("is-loading");
      const spinner = document.createElement("span");
      spinner.className = "cloze-btn-spinner";
      btn.appendChild(spinner);
    } else {
      const iconEl = btn.createSpan({ cls: "cloze-btn-icon" });
      const icon = (0, import_obsidian4.getIcon)(iconName);
      if (icon)
        iconEl.appendChild(icon);
    }
    btn.createSpan({ text: label, cls: "cloze-btn-label" });
    if (disabled) {
      btn.disabled = true;
    } else {
      btn.addEventListener("click", (e) => {
        e.preventDefault();
        onClick();
      });
    }
    return btn;
  }
  createIconButton(iconName, onClick) {
    const btn = document.createElement("button");
    btn.className = "cloze-toolbar-btn cloze-btn-icon-only";
    const icon = (0, import_obsidian4.getIcon)(iconName);
    if (icon)
      btn.appendChild(icon);
    btn.addEventListener("click", (e) => {
      e.preventDefault();
      onClick();
    });
    return btn;
  }
  hide() {
    if (this.toolbarEl) {
      this.toolbarEl.remove();
      this.toolbarEl = null;
    }
    if (this.containerEl) {
      this.containerEl.classList.remove("has-cloze-toolbar");
      this.containerEl = null;
    }
    this.leftGroup = null;
    this.centerGroup = null;
    this.statusEl = null;
  }
  destroy() {
    this.hide();
  }
};

// src/i18n.ts
var LOCALES = {
  zh: {
    ready: "\u5C31\u7EEA",
    aiGenerate: "AI \u6316\u7A7A",
    generating: "\u751F\u6210\u4E2D\u2026",
    aiGenerating: "AI \u751F\u6210\u4E2D\u2026",
    showAnswer: "\u663E\u793A\u7B54\u6848",
    reset: "\u91CD\u7F6E",
    exitReview: "\u9000\u51FA\u590D\u4E60",
    startReview: "\u5F00\u59CB\u590D\u4E60",
    clozesCount: "\u4E2A\u6316\u7A7A",
    reviewOn: "\u6316\u7A7A\u590D\u4E60\u6A21\u5F0F\u5DF2\u5F00\u542F",
    reviewOff: "\u6316\u7A7A\u590D\u4E60\u6A21\u5F0F\u5DF2\u5173\u95ED",
    openNoteFirst: "\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u7B14\u8BB0",
    generateFirst: "\u8BF7\u5148\u751F\u6210\u6316\u7A7A\u5185\u5BB9",
    allRevealed: "\u5DF2\u663E\u793A\u6240\u6709\u7B54\u6848",
    activateFirst: "\u8BF7\u5148\u5F00\u542F\u590D\u4E60\u6A21\u5F0F",
    aiGeneratingTitle: "AI \u6B63\u5728\u751F\u6210\u6316\u7A7A\u2026",
    noContent: "\u6CA1\u6709\u53EF\u6316\u7A7A\u7684\u5185\u5BB9",
    configApiKey: "\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E API Key",
    configModel: "\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E\u6A21\u578B\u540D\u79F0",
    generated: "\u6316\u7A7A\u751F\u6210\u5B8C\u6210\uFF01\u5171",
    genFailed: "AI \u751F\u6210\u5931\u8D25: ",
    noCache: "\u6CA1\u6709\u7F13\u5B58\u7684\u6316\u7A7A\u5185\u5BB9\uFF0C\u8BF7\u5148\u70B9\u51FB AI \u6316\u7A7A",
    apiFailed: "API \u8BF7\u6C42\u5931\u8D25",
    aiEmpty: "AI \u8FD4\u56DE\u5185\u5BB9\u4E3A\u7A7A",
    aiConfig: "AI \u914D\u7F6E",
    apiEndpoint: "API \u7AEF\u70B9",
    apiEndpointDesc: "OpenAI \u517C\u5BB9\u7684 API \u5730\u5740\uFF08\u652F\u6301 OpenAI / \u667A\u8C31 / Moonshot / Ollama \u7B49\uFF09",
    apiKey: "API Key",
    apiKeyDesc: "API \u5BC6\u94A5",
    model: "\u6A21\u578B",
    modelDesc: "\u4F7F\u7528\u7684\u6A21\u578B\u540D\u79F0",
    temperature: "\u6E29\u5EA6",
    temperatureDesc: "\u751F\u6210\u6E29\u5EA6 (0-1)\uFF0C\u8D8A\u4F4E\u8D8A\u786E\u5B9A\u6027",
    clozeSettings: "\u6316\u7A7A\u8BBE\u7F6E",
    difficulty: "\u96BE\u5EA6",
    difficultyDesc: "\u6316\u7A7A\u5BC6\u5EA6\u6839\u636E\u5185\u5BB9\u957F\u5EA6\u548C\u96BE\u5EA6\u81EA\u52A8\u8BA1\u7B97",
    easy: "\u7B80\u5355 - \u7A00\u758F\uFF0C\u53EA\u6316\u6700\u6838\u5FC3\u5185\u5BB9",
    medium: "\u4E2D\u7B49 - \u9002\u5EA6\u6316\u7A7A",
    hard: "\u56F0\u96BE - \u5BC6\u96C6\u6316\u7A7A",
    extreme: "\u8D85\u5BC6\u96C6 - \u51E0\u4E4E\u8986\u76D6\u6240\u6709\u77E5\u8BC6\u70B9",
    autoReview: "\u81EA\u52A8\u8FDB\u5165\u590D\u4E60\u6A21\u5F0F",
    autoReviewDesc: "AI \u751F\u6210\u6316\u7A7A\u540E\u81EA\u52A8\u8FDB\u5165\u590D\u4E60\u6A21\u5F0F",
    customPrompt: "\u81EA\u5B9A\u4E49\u63D0\u793A\u8BCD",
    customPromptDesc: "\u7559\u7A7A\u5219\u4F7F\u7528\u9ED8\u8BA4\u63D0\u793A\u8BCD",
    language: "\u8BED\u8A00",
    languageDesc: "\u754C\u9762\u8BED\u8A00",
    chinese: "\u4E2D\u6587",
    english: "English",
    clozeSyntax: "\u6316\u7A7A\u8BED\u6CD5",
    basicCloze: "\u57FA\u672C\u6316\u7A7A",
    hintCloze: "\u5E26\u63D0\u793A\u7684\u6316\u7A7A",
    autoCalc: "\u6316\u7A7A\u6570\u91CF\u6839\u636E\u7B14\u8BB0\u5185\u5BB9\u957F\u5EA6\u548C\u96BE\u5EA6\u81EA\u52A8\u8BA1\u7B97\uFF0C\u65E0\u9700\u624B\u52A8\u8BBE\u7F6E\u3002",
    readingDesc: "\u5728\u9605\u8BFB\u89C6\u56FE\u4E2D\uFF0C\u590D\u4E60\u6A21\u5F0F\u4F1A\u5C06\u6316\u7A7A\u5185\u5BB9\u9690\u85CF\u4E3A\u7A7A\u767D\uFF0C\u70B9\u51FB\u53EF\u663E\u793A\u7B54\u6848\u3002",
    cmdAiGenerate: "AI \u751F\u6210\u6316\u7A7A",
    cmdStartReview: "\u5F00\u59CB\u590D\u4E60\uFF08\u4F7F\u7528\u7F13\u5B58\uFF09",
    cmdToggleReview: "\u5207\u6362\u590D\u4E60\u6A21\u5F0F",
    cmdShowReset: "\u663E\u793A/\u91CD\u7F6E\u7B54\u6848",
    placeholder: "\uFF3B \uFF3D",
    defaultPrompt: `\u4F60\u662F\u4E00\u4E2A\u5B66\u4E60\u8F85\u52A9\u5DE5\u5177\u3002\u8BF7\u5206\u6790\u4EE5\u4E0B\u7B14\u8BB0\u5185\u5BB9\uFF0C\u8BC6\u522B\u5176\u4E2D\u7684\u91CD\u70B9\u5185\u5BB9\uFF08\u5982\u5173\u952E\u6982\u5FF5\u3001\u5B9A\u4E49\u3001\u672F\u8BED\u3001\u65E5\u671F\u3001\u6570\u5B57\u3001\u516C\u5F0F\u3001\u4EBA\u540D\u3001\u5730\u540D\u3001\u6838\u5FC3\u8BBA\u70B9\u7B49\uFF09\uFF0C\u5E76\u5C06\u8FD9\u4E9B\u91CD\u8981\u5185\u5BB9\u7528\u6316\u7A7A\u683C\u5F0F {{c1::\u5185\u5BB9}} \u5305\u88F9\u8D77\u6765\u3002

\u8981\u6C42\uFF1A
1. \u53EA\u5BF9\u503C\u5F97\u8BB0\u5FC6\u7684\u91CD\u8981\u4FE1\u606F\u8FDB\u884C\u6316\u7A7A\uFF0C\u4E0D\u8981\u8FC7\u5EA6\u6316\u7A7A
2. \u6BCF\u4E2A\u6316\u7A7A\u5E94\u8BE5\u662F\u4E00\u4E2A\u5B8C\u6574\u7684\u3001\u6709\u610F\u4E49\u7684\u5185\u5BB9\u7247\u6BB5
3. \u4FDD\u6301\u539F\u6587\u7ED3\u6784\u548C\u683C\u5F0F\u4E0D\u53D8\uFF0C\u53EA\u6DFB\u52A0\u6316\u7A7A\u6807\u8BB0
4. \u5BF9\u4E8E\u9700\u8981\u63D0\u793A\u7684\u5185\u5BB9\uFF0C\u53EF\u4EE5\u4F7F\u7528 {{c1::\u5185\u5BB9::\u63D0\u793A}} \u683C\u5F0F
5. \u6316\u7A7A\u6570\u91CF\u9002\u4E2D\uFF0C\u91CD\u70B9\u7A81\u51FA
6. \u4E0D\u8981\u5BF9\u6807\u9898\u3001\u5217\u8868\u6807\u8BB0\u3001\u94FE\u63A5\u7B49\u7ED3\u6784\u5143\u7D20\u8FDB\u884C\u6316\u7A7A
7. \u76F4\u63A5\u8FD4\u56DE\u4FEE\u6539\u540E\u7684\u5B8C\u6574\u5185\u5BB9\uFF0C\u4E0D\u8981\u6DFB\u52A0\u4EFB\u4F55\u989D\u5916\u8BF4\u660E\u6216\u89E3\u91CA`,
    diffHintEasy: "\u53EA\u5BF9\u6700\u6838\u5FC3\u7684\u5173\u952E\u8BCD\u3001\u4E13\u6709\u540D\u8BCD\u3001\u91CD\u8981\u6570\u5B57\u8FDB\u884C\u6316\u7A7A\uFF0C\u6BCF\u6BB5\u6700\u591A1-2\u4E2A\u6316\u7A7A\u3002",
    diffHintMedium: "\u5BF9\u5173\u952E\u6982\u5FF5\u3001\u5B9A\u4E49\u4E2D\u7684\u6838\u5FC3\u8BCD\u3001\u91CD\u8981\u672F\u8BED\u8FDB\u884C\u6316\u7A7A\uFF0C\u9002\u5EA6\u8986\u76D6\u91CD\u70B9\u5185\u5BB9\u3002",
    diffHintHard: "\u5BC6\u96C6\u6316\u7A7A\uFF0C\u5BF9\u6240\u6709\u91CD\u8981\u4FE1\u606F\u70B9\u90FD\u8FDB\u884C\u6316\u7A7A\uFF0C\u5305\u62EC\u7EC6\u8282\u6027\u7684\u6570\u5B57\u3001\u65E5\u671F\u3001\u4EBA\u540D\u7B49\u3002",
    diffHintExtreme: "\u8D85\u5BC6\u96C6\u6316\u7A7A\uFF0C\u51E0\u4E4E\u5BF9\u6BCF\u4E2A\u6709\u610F\u4E49\u7684\u8BCD\u7EC4\u90FD\u8FDB\u884C\u6316\u7A7A\uFF0C\u6700\u5927\u9650\u5EA6\u5730\u8986\u76D6\u77E5\u8BC6\u70B9\uFF0C\u8BA9\u590D\u4E60\u6781\u5177\u6311\u6218\u6027\u3002",
    clozeCountHint: "\u6839\u636E\u5185\u5BB9\u957F\u5EA6\uFF0C\u5927\u7EA6\u6316\u7A7A {0} \u4E2A\uFF0C\u6839\u636E\u5B9E\u9645\u91CD\u70B9\u7075\u6D3B\u8C03\u6574\u3002",
    systemSuffix: "\u91CD\u8981\uFF1A\u4F60\u5FC5\u987B\u4F7F\u7528 {{c1::\u5185\u5BB9}} \u683C\u5F0F\u5305\u88F9\u91CD\u8981\u4FE1\u606F\u3002\u76F4\u63A5\u8FD4\u56DE\u4FEE\u6539\u540E\u7684\u5B8C\u6574\u5185\u5BB9\uFF0C\u4E0D\u8981\u6DFB\u52A0\u4EFB\u4F55\u89E3\u91CA\u6216\u8BF4\u660E\u3002",
    userMessagePrefix: "\u8BF7\u5BF9\u4EE5\u4E0B\u7B14\u8BB0\u5185\u5BB9\u8FDB\u884C\u6316\u7A7A\u5904\u7406\uFF0C\u7528 {{c1::\u5185\u5BB9}} \u683C\u5F0F\u5305\u88F9\u91CD\u8981\u4FE1\u606F\uFF0C\u8FD4\u56DE\u5B8C\u6574\u7684\u4FEE\u6539\u540E\u5185\u5BB9\uFF1A",
    chunkHint: "\uFF08\u672C\u6BB5\u5927\u7EA6\u6316\u7A7A {0} \u4E2A\uFF09",
    testConnection: "\u6D4B\u8BD5\u8FDE\u63A5",
    testing: "\u6D4B\u8BD5\u4E2D\u2026",
    testSuccess: "\u8FDE\u63A5\u6210\u529F\uFF01\u6A21\u578B\u53EF\u7528",
    testFailed: "\u8FDE\u63A5\u5931\u8D25: ",
    configEndpoint: "\u8BF7\u5148\u914D\u7F6E API \u7AEF\u70B9"
  },
  en: {
    ready: "Ready",
    aiGenerate: "AI Cloze",
    generating: "Generating\u2026",
    aiGenerating: "AI generating\u2026",
    showAnswer: "Reveal",
    reset: "Reset",
    exitReview: "Exit",
    startReview: "Review",
    clozesCount: " clozes",
    reviewOn: "Review mode activated",
    reviewOff: "Review mode deactivated",
    openNoteFirst: "Please open a note first",
    generateFirst: "Please generate clozes first",
    allRevealed: "All answers revealed",
    activateFirst: "Please activate review mode first",
    aiGeneratingTitle: "AI generating clozes\u2026",
    noContent: "No content to cloze",
    configApiKey: "Please configure API key in settings",
    configModel: "Please configure model name in settings",
    generated: "Generated ",
    genFailed: "AI generation failed: ",
    noCache: "No cached cloze content. Click AI Cloze first.",
    apiFailed: "API request failed",
    aiEmpty: "AI returned empty content",
    aiConfig: "AI Configuration",
    apiEndpoint: "API Endpoint",
    apiEndpointDesc: "OpenAI-compatible API URL",
    apiKey: "API Key",
    apiKeyDesc: "Your API key",
    model: "Model",
    modelDesc: "Model name to use",
    temperature: "Temperature",
    temperatureDesc: "Generation temperature (0-1)",
    clozeSettings: "Cloze Settings",
    difficulty: "Difficulty",
    difficultyDesc: "Density auto-calculated from content length and difficulty",
    easy: "Easy - sparse, keywords only",
    medium: "Medium - moderate coverage",
    hard: "Hard - dense coverage",
    extreme: "Extreme - full coverage",
    autoReview: "Auto enter review",
    autoReviewDesc: "Automatically enter review after AI generation",
    customPrompt: "Custom prompt",
    customPromptDesc: "Leave empty to use default prompt",
    language: "Language",
    languageDesc: "Interface language",
    chinese: "\u4E2D\u6587",
    english: "English",
    clozeSyntax: "Cloze Syntax",
    basicCloze: "Basic cloze",
    hintCloze: "Cloze with hint",
    autoCalc: "Cloze count is auto-calculated from content length and difficulty.",
    readingDesc: "In reading view, review mode hides cloze answers as blanks, click to reveal.",
    cmdAiGenerate: "AI generate clozes",
    cmdStartReview: "Start review (use cache)",
    cmdToggleReview: "Toggle review mode",
    cmdShowReset: "Show/Reset answers",
    placeholder: "[ __ ]",
    defaultPrompt: `You are a study aid tool. Analyze the following note content, identify key points (such as key concepts, definitions, terms, dates, numbers, formulas, names, places, core arguments, etc.), and wrap these important contents in cloze format {{c1::content}}.

Requirements:
1. Only cloze information worth memorizing, do not over-cloze
2. Each cloze should be a complete, meaningful content fragment
3. Keep the original structure and format unchanged, only add cloze markers
4. For content that needs hints, use {{c1::content::hint}} format
5. Moderate number of clozes, focus on key points
6. Do not cloze structural elements like titles, list markers, links, etc.
7. Return the modified complete content directly, without adding any extra explanation`,
    diffHintEasy: "Only cloze the most core keywords, proper nouns, and important numbers, at most 1-2 clozes per paragraph.",
    diffHintMedium: "Cloze key concepts, core words in definitions, and important terms, with moderate coverage of key content.",
    diffHintHard: "Dense clozing, cloze all important information points, including detailed numbers, dates, names, etc.",
    diffHintExtreme: "Ultra-dense clozing, cloze almost every meaningful phrase, maximally covering knowledge points for challenging review.",
    clozeCountHint: "Based on content length, approximately {0} clozes, adjust flexibly based on actual key points.",
    systemSuffix: "Important: You must use {{c1::content}} format to wrap important information. Return the modified complete content directly, without adding any explanation.",
    userMessagePrefix: "Please cloze the following note content, wrapping important information in {{c1::content}} format, and return the complete modified content:",
    chunkHint: "(Approximately {0} clozes in this section)",
    testConnection: "Test Connection",
    testing: "Testing\u2026",
    testSuccess: "Connection successful! Model is available",
    testFailed: "Connection failed: ",
    configEndpoint: "Please configure API endpoint first"
  }
};
function getLocale(lang) {
  return LOCALES[lang] || LOCALES.en;
}
function detectLanguage() {
  var _a;
  try {
    const lang = (_a = navigator.language) == null ? void 0 : _a.toLowerCase();
    if (lang && (lang.startsWith("zh") || lang.includes("cn")))
      return "zh";
  } catch (e) {
  }
  return "en";
}

// main.ts
var ClozeReviewPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    __publicField(this, "settings");
    __publicField(this, "aiService");
    __publicField(this, "clozeParser");
    __publicField(this, "reviewMode");
    __publicField(this, "toolbar");
    __publicField(this, "clozeCache", /* @__PURE__ */ new Map());
    __publicField(this, "generating", false);
    __publicField(this, "_t", getLocale("en"));
  }
  get t() {
    return this._t;
  }
  updateLang() {
    const lang = this.settings.lang === "auto" ? detectLanguage() : this.settings.lang;
    this._t = getLocale(lang);
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new ClozeReviewSettingTab(this.app, this));
    this.updateLang();
    this.aiService = new AIService(this.settings);
    this.clozeParser = new ClozeParser();
    this.reviewMode = new ReviewMode(this.app, this);
    this.toolbar = new BottomToolbar(this.app, this);
    this.registerMarkdownPostProcessor((el, _ctx) => {
      this.reviewMode.processElement(el);
    });
    this.toolbar.init();
    this.addCommand({
      id: "ai-generate-cloze",
      name: this.t.cmdAiGenerate,
      callback: () => this.generateCloze()
    });
    this.addCommand({
      id: "start-review",
      name: this.t.cmdStartReview,
      callback: () => this.startReview()
    });
    this.addCommand({
      id: "toggle-review-mode",
      name: this.t.cmdToggleReview,
      callback: () => {
        if (this.reviewMode.isActive()) {
          this.reviewMode.deactivate();
        } else {
          this.startReview();
        }
        this.toolbar.refresh();
      }
    });
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        if (this.reviewMode.isActive()) {
          this.reviewMode.deactivate(true);
          const view = this.getMarkdownView();
          if (view && view.file && this.clozeCache.has(view.file.path)) {
            setTimeout(async () => {
              await this.reviewMode.activate(true);
              this.toolbar.refresh();
            }, 500);
            return;
          }
        }
        this.toolbar.refresh();
      })
    );
  }
  isGenerating() {
    return this.generating;
  }
  async startReview() {
    if (this.reviewMode.isActive())
      return;
    const view = this.getMarkdownView();
    if (!view || !view.file) {
      new import_obsidian5.Notice(this.t.openNoteFirst);
      return;
    }
    if (!this.clozeCache.has(view.file.path)) {
      new import_obsidian5.Notice(this.t.noCache);
      return;
    }
    await this.reviewMode.activate();
    this.toolbar.refresh();
  }
  async generateCloze() {
    if (this.generating)
      return;
    const view = this.getMarkdownView();
    if (!view || !view.file) {
      new import_obsidian5.Notice(this.t.openNoteFirst);
      return;
    }
    this.generating = true;
    this.toolbar.refresh();
    const notice = new import_obsidian5.Notice(this.t.aiGeneratingTitle, 0);
    try {
      const editor = view.editor;
      const selection = editor.getSelection();
      const content = selection || editor.getValue();
      if (!content.trim()) {
        new import_obsidian5.Notice(this.t.noContent);
        return;
      }
      if (!this.settings.apiKey) {
        new import_obsidian5.Notice(this.t.configApiKey);
        this.openSettings();
        return;
      }
      if (!this.settings.model) {
        new import_obsidian5.Notice(this.t.configModel);
        this.openSettings();
        return;
      }
      this.aiService.updateSettings(this.settings);
      const result = await this.aiService.generateCloze(content, this.settings.customPrompt, this._t);
      this.clozeCache.set(view.file.path, result);
      notice.hide();
      const clozeCount = this.clozeParser.count(result);
      new import_obsidian5.Notice(`${this.t.generated} ${clozeCount} ${this.t.clozesCount}`);
      if (this.settings.autoEnterReview) {
        if (this.reviewMode.isActive()) {
          await this.reviewMode.deactivate();
        }
        await this.reviewMode.activate();
      }
    } catch (e) {
      notice.hide();
      new import_obsidian5.Notice(this.t.genFailed + e.message, 5e3);
      console.error("Cloze generation error:", e);
    } finally {
      this.generating = false;
      this.toolbar.refresh();
    }
  }
  getMarkdownView() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
    if (activeView)
      return activeView;
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    if (leaves.length > 0)
      return leaves[0].view;
    return null;
  }
  openSettings() {
    this.app.setting.open();
    this.app.setting.openTabById("ai-cloze-review");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    var _a;
    await this.saveData(this.settings);
    (_a = this.aiService) == null ? void 0 : _a.updateSettings(this.settings);
  }
  onunload() {
    this.reviewMode.destroy();
    this.toolbar.destroy();
    document.querySelectorAll(".cloze-review-toolbar").forEach((el) => el.remove());
    document.querySelectorAll(".cloze-review-active").forEach((el) => {
      el.classList.remove("cloze-review-active");
    });
  }
};
